export const PRODOTTI= [
   

        {
            "id": 1,
            "nome": "Nike Air Max 270",
            "categoria": "Sneakers",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Grigio", "Blu", "Rosso"],
            "descrizione": "Le Nike Air Max 270 offrono un comfort incredibile grazie all'ammortizzazione Air Max. Ideali per l'uso quotidiano e l'attività sportiva.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/skwgyqrbfzhu6uyeh0gg/scarpa-air-max-270-Kqzbp7.png",
            "scarpa1": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ekooqxmzujps9pj0vlak/scarpa-air-max-270-Kqzbp7.png",
            "nuovo_arrivi": true,
           
            "Trend_della_settimana":true
          },
          {
            "id": 2,
            "nome": "Nike React Infinity Run Flyknit",
            "categoria": "Running",
            "prezzo": 159.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Giallo", "Grigio/Blu", "Bianco/Rosso", "Verde", "Blu"],
            "descrizione": "Le Nike React Infinity Run Flyknit sono progettate per la massima ammortizzazione e stabilità durante la corsa. Con tomaia in Flyknit per un comfort superiore.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/df6a994a-bc85-4637-94bf-3ae4af43a8fe/scarpa-da-running-su-strada-infinityrn-4-GM5ls9.png",
            "nuovo_arrivi": true,
            "Trend_della_settimana":true
            
          },
          {
            "id": 3,
            "nome": "Nike Air Force 1",
            "categoria": "Sneakers",
            "prezzo": 109.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Bianco", "Nero", "Rosso", "Blu", "Grigio"],
            "descrizione": "Le Nike Air Force 1 sono un'icona streetwear, caratterizzate da un design classico e un comfort eccezionale.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fc4622c4-2769-4665-aa6e-42c974a7705e/scarpa-air-force-1-07-HvZlfx.png",
            "nuovo_arrivi": true,
            "Trend_della_settimana":true
           
          },
          {
            "id": 4,
            "nome": "Nike Air Zoom Pegasus 38",
            "categoria": "Running",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Grigio/Arancione", "Bianco/Nero", "Blu/Verde", "Rosso", "Nero"],
            "descrizione": "Le Nike Air Zoom Pegasus 38 offrono una corsa reattiva e ammortizzata grazie all'unità Zoom Air. Ideali per runner di tutti i livelli.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/52c7509c-8f27-4860-a869-a0e23912daf8/scarpa-da-running-su-strada-pegasus-40-M88nP6.png",
           "best_seller": 5,

          },
          {
            "id": 5,
            "nome": "Nike Air Jordan 1 Mid",
            "categoria": "Basket",
            "prezzo": 149.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Rosso", "Bianco/Nero", "Blu/Rosso", "Verde", "Rosso/Bianco"],
            "descrizione": "Le Nike Air Jordan 1 Mid sono scarpe da basket iconiche, ispirate al modello originale del 1985. Confortevoli e dal look distintivo.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/6dd5c76b-c124-45f3-952e-a89d0741bcdf/scarpa-air-jordan-1-mid-se-bcVdbQ.png",
            "Trend_della_settimana":true
          },
          {
            "id": 6,
            "nome": "Nike Revolution 5",
            "categoria": "Running",
            "prezzo": 79.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Grigio", "Blu", "Rosso"],
            "descrizione": "Le Nike Revolution 5 sono scarpe leggere e traspiranti, ideali per correre o per l'uso quotidiano. Ottimo rapporto qualità-prezzo.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7df57edf-bdc6-4320-a956-8ce37228cd1d/scarpa-da-running-su-strada-revolution-6-FgfhgR.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          {
            "id": 7,
            "nome": "Nike Air Zoom Structure 24",
            "categoria": "Running",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Grigio", "Bianco/Nero", "Blu", "Rosso", "Verde"],
            "descrizione": "Le Nike Air Zoom Structure 24 sono scarpe da corsa stabili e ammortizzate, ideali per runner che cercano supporto e comfort.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/de277aba-3e31-4c0c-b95e-505b000457f5/scarpa-da-running-su-strada-structure-25-4pHGTM.png",
           "best_seller": 5,

            
          },
          {
            "id": 8,
            "nome": "Nike Air Max 97",
            "categoria": "Sneakers",
            "prezzo": 179.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Argento", "Nero", "Oro", "Rosso", "Bianco"],
            "descrizione": "Le Nike Air Max 97 sono sneakers iconiche caratterizzate da un design futuristico e un'ammortizzazione leggendaria.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5fe30fc4-2645-4d1e-b3f8-70da145e0f74/scarpa-air-max-97-nsRddC.png",
           "best_seller": 5,

        
          },
          {
            "id": 9,
            "nome": "Nike Air Zoom Terra Kiger 7",
            "categoria": "Trail Running",
            "prezzo": 139.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Grigio", "Blu", "Verde", "Rosso", "Arancione"],
            "descrizione": "Le Nike Air Zoom Terra Kiger 7 sono progettate per il trail running, offrendo trazione e stabilità su terreni accidentati.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/eeec418c-382f-4740-bc04-1ae992337748/scarpa-da-trail-running-kiger-9-qg9HC0.png",
           "best_seller": 5,

            
          },
          {
            "id": 10,
            "nome": "Nike Air VaporMax Plus",
            "categoria": "Sneakers",
            "prezzo": 209.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Verde"],
            "descrizione": "Le Nike Air VaporMax Plus offrono un'esperienza di corsa leggera e reattiva grazie all'unità VaporMax a tutta lunghezza.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6ff6e596-2f93-47f8-98a4-611de407bffb/scarpa-air-vapormax-2023-flyknit-PMlg2D.png",
            "nuovo_arrivi": true,
           "best_seller": 5,


          },
          {
            "id": 11,
            "nome": "Nike Air Max 90",
            "categoria": "Sneakers",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max 90 sono sneakers classiche con dettagli iconici, offrendo comfort e stile per tutti i giorni.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/da0ad10d-dbd6-4fd4-885a-b6e5b306a8a6/scarpa-air-max-90-QMcHLr.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          {
            "id": 12,
            "nome": "Nike Air Zoom Vomero 16",
            "categoria": "Running",
            "prezzo": 149.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Verde"],
            "descrizione": "Le Nike Air Zoom Vomero 16 sono scarpe da corsa ammortizzate e reattive, ideali per lunghe distanze e allenamenti intensi.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8ea07629-c4e8-4c23-aed7-e2f45f8f6d7d/scarpa-da-running-su-strada-vomero-17-RsQ4DC.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 13,
            "nome": "Nike Air Jordan 4 Retro",
            "categoria": "Basket",
            "prezzo": 199.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Rosso", "Bianco/Nero", "Blu/Rosso", "Grigio", "Verde"],
            "descrizione": "Le Nike Air Jordan 4 Retro sono scarpe da basket iconiche con dettagli classici e comfort eccezionale.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/495ec78a-f467-4064-888e-124d27994023/scarpa-jordan-4-retro-a-RDdBhh.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          {
            "id": 14,
            "nome": "Nike Blazer Mid '77 Vintage",
            "categoria": "Sneakers",
            "prezzo": 99.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Bianco", "Nero", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Blazer Mid '77 Vintage sono sneakers retrò con uno stile distintivo e una tomaia in pelle premium.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/389b709e-5102-4e55-aa5d-07099b500831/scarpa-blazer-mid-77-vintage-hk4NZb.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          {
            "id": 15,
            "nome": "Nike Air Max Excee",
            "categoria": "Sneakers",
            "prezzo": 89.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Bianco", "Nero", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Excee sono ispirate alle iconiche Air Max 90, offrendo comfort e stile in un design moderno.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a77e2c37-8bd5-4030-83ec-6c005cba7b69/scarpa-air-max-excee-9RM6nF.png",
           "best_seller": 5,

          },
          {
            "id": 16,
            "nome": "Nike Air Zoom SuperRep 2",
            "categoria": "Training",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Verde"],
            "descrizione": "Le Nike Air Zoom SuperRep 2 sono scarpe da training con ammortizzazione reattiva e supporto per gli allenamenti più intensi.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d1221ac8-447b-4e7e-8321-292c533cbb25/scarpa-da-allenamento-zoom-superrep-4-next-nature-LL5XVP.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          {
            "id": 17,
            "nome": "Nike Air Zoom Freak 3",
            "categoria": "Basket",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero/Bianco", "Rosso/Nero", "Blu", "Grigio", "Verde"],
            "descrizione": "Le Nike Air Zoom Freak 3 sono scarpe da basket progettate per la potenza e la velocità di Giannis Antetokounmpo. Massima trazione e stabilità.",
            "immagine": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c21dfe7c-c04a-4efb-ab0d-10123a303c67/custom-freak-5-by-you.png",
           "best_seller": 5,

          },
          {
            "id": 18,
            "nome": "Nike Renew Run",
            "categoria": "Running",
            "prezzo": 99.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Verde"],
            "descrizione": "Le Nike Renew Run sono scarpe da corsa ammortizzate e leggere, ideali per corridori di tutti i livelli.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b05afb11-db22-461d-b94e-49bdc316b445/scarpa-da-running-su-strada-revolution-6-FgfhgR.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 19,
            "nome": "Nike Air Max Sequent 4",
            "categoria": "Sneakers",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Sequent 4 sono scarpe da corsa comode e versatili, ideali per l'uso quotidiano o l'allenamento leggero.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5e96bd0c-a7dc-4db6-9aec-520f243967c7/scarpa-air-max-sc-MFQFCf.png",
           "best_seller": 5,

          },
          {
            "id": 20,
            "nome": "Nike Air Max 2090",
            "categoria": "Sneakers",
            "prezzo": 149.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max 2090 sono ispirate all'iconica Air Max 90, con un design futuristico e un'ammortizzazione avanzata.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f50070d2-77a3-4213-aebf-9371d9759548/scarpa-air-max-dn-SBVfbL.png",
            "nuovo_arrivi": true,
           "best_seller": 5,

          },
          
          {
            "id": 21,
            "nome": "Nike Joyride Run Flyknit",
            "categoria": "Running",
            "prezzo": 159.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Joyride Run Flyknit offrono un'esperienza di corsa rivoluzionaria grazie alla tecnologia di ammortizzazione a microsfere.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/de19560f-411b-412f-a6a6-ddf9c33e7fbd/scarpa-da-running-su-strada-invincible-3-9lqlcK.png",
           "best_seller": 5,

          },
          {
            "id": 22,
            "nome": "Nike Air Max Tailwind IV",
            "categoria": "Sneakers",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Tailwind IV sono scarpe da running retrò con un'ammortizzazione Air Max e uno stile distintivo.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/35088631-7920-4f60-bff1-52de1bb15fa2/scarpa-air-max-90-pTwmcS.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 23,
            "nome": "Nike Air Zoom Structure 23",
            "categoria": "Running",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Structure 23 offrono supporto e stabilità per i runner, con un'ammortizzazione reattiva e una tomaia traspirante.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d8c80658-d66b-436e-aa07-41430f2d19de/scarpa-da-running-su-strada-structure-25-4pHGTM.png",
           "best_seller": 5,

          },
          {
            "id": 24,
            "nome": "Nike Air Max 270 React",
            "categoria": "Sneakers",
            "prezzo": 159.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max 270 React uniscono il comfort dell'unità Air Max con la reattività della tecnologia React.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e17c5d07-0f6f-4476-9a1c-6542c80e783c/scarpa-air-max-270-LnQWdW.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 25,
            "nome": "Nike Air Zoom Wildhorse 7",
            "categoria": "Trail Running",
            "prezzo": 139.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Wildhorse 7 sono scarpe da trail running progettate per la massima trazione e stabilità su terreni accidentati.",
            "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7f0793f2-f6c0-440c-b6c1-894060cef0e1/scarpa-da-trail-running-wildhorse-8-8TtPPV.png",
           "best_seller": 5,

          },
          {
            "id": 26,
            "nome": "Nike React Infinity Run Flyknit 2",
            "categoria": "Running",
            "prezzo": 169.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike React Infinity Run Flyknit 2 sono scarpe da corsa con una tomaia in Flyknit e un'ammortizzazione reattiva per una corsa fluida.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e5525978-9342-4727-a88f-850302deefc7/scarpa-da-running-su-strada-infinityrn-4-XMthvP.png",
           "best_seller": 5,

          },
          {
            "id": 27,
            "nome": "Nike Air Zoom SuperRep",
            "categoria": "Training",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom SuperRep sono scarpe da training con un'ammortizzazione reattiva e una suola stabile per gli esercizi in palestra.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d1221ac8-447b-4e7e-8321-292c533cbb25/scarpa-da-allenamento-zoom-superrep-4-next-nature-LL5XVP.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 28,
            "nome": "Nike Air Zoom Freak 2",
            "categoria": "Basket",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Freak 2 sono scarpe da basket con un'ammortizzazione reattiva e un design ispirato a Giannis Antetokounmpo.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ad357d4a-4616-4320-9317-0447727aba5e/scarpa-da-basket-giannis-freak-5-xm39LW.png",
           "best_seller": 5,

          },
          {
            "id": 29,
            "nome": "Nike Metcon 7",
            "categoria": "Training",
            "prezzo": 139.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Metcon 7 sono scarpe da training progettate per la stabilità e la resistenza, ideali per gli allenamenti più intensi.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b6020618-729d-4873-9c5f-6b295fa2bee7/scarpa-da-allenamento-metcon-9-amp-H9t4mr.png",
           "best_seller": 5,

          },
          {
            "id": 30,
            "nome": "Nike React Element 55",
            "categoria": "Sneakers",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike React Element 55 sono sneakers confortevoli e leggere, ideali per lo stile quotidiano.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8c5d638a-9701-42ae-8aa6-61251d244725/scarpa-acg-mountain-fly-2-low-gore-tex-pkR8xh.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 31,
            "nome": "Nike Air Max 95",
            "categoria": "Sneakers",
            "prezzo": 159.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max 95 sono scarpe iconiche con un design distintivo e un'ammortizzazione Air Max visibile.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/c8be2a06-d430-4c73-addc-90dde145c9ff/scarpa-air-max-95-LtLM1W.png",
           "best_seller": 5,

          },
          {
            "id": 32,
            "nome": "Nike Air Zoom Winflo 8",
            "categoria": "Running",
            "prezzo": 109.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Winflo 8 sono scarpe da corsa leggere e reattive, ideali per allenamenti e gare su strada.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/87b891f6-1e93-4e82-b34d-dbfb5d836e17/scarpa-da-running-su-strada-wio-10-LGNPTB.png",
            "nuovo_arrivi": true,
          },
          {
            "id": 33,
            "nome": "Nike Air Force 1 React",
            "categoria": "Sneakers",
            "prezzo": 119.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Force 1 React uniscono il classico stile delle Air Force 1 con la reattività della tecnologia React.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/zrhpg00meg0lsfrgkzkq/scarpa-air-force-1-flyknit-2-L5q9GR.png",
           "best_seller": 5,

          },
          {
            "id": 34,
            "nome": "Nike Air Max Bella TR 4",
            "categoria": "Training",
            "prezzo": 89.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Bella TR 4 sono scarpe da training leggere e flessibili, ideali per gli allenamenti in palestra o all'aperto.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ba9a0cd9-d8c1-429d-9145-26b07998698c/scarpa-da-allenamento-air-zoom-tr-1-GjSF3c.png",
            "nuovo_arrivi": true,
          },
          
          
          {
            "id": 35,
            "nome": "Nike Air Max Plus",
            "categoria": "Sneakers",
            "prezzo": 169.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Plus sono sneakers iconiche con un design audace e un'ammortizzazione Max Air per il massimo comfort.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/c6cnf0x5ggrmrysnryei/scarpa-air-max-plus-nJPFW8.png",
            "nuovo_arrivi": true,
          },

          {
            "id": 36,
            "nome": "Nike Air Zoom Tempo Next%",
            "categoria": "Running",
            "prezzo": 199.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Tempo Next% sono scarpe da corsa ad alte prestazioni con tecnologia ZoomX per la massima reattività.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1c4cb9ff-ec3a-4acf-9129-410bad60e1bc/scarpa-da-basket-lebron-xxi-queen-conch-JKS8Sf.png",
            "nuovo_arrivi": true,
        },
        {
            "id": 37,
            "nome": "Nike Air Force 1 Low",
            "categoria": "Sneakers",
            "prezzo": 109.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Force 1 Low sono un classico intramontabile, ideali per un look casual e confortevole.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/38a5118d-6c57-430c-9f15-7c21f7bf40e5/scarpa-air-force-1-low-evo-rLlvX9.png",
           "best_seller": 5,

        },
        {
            "id": 38,
            "nome": "Nike Air Zoom Alphafly NEXT%",
            "categoria": "Running",
            "prezzo": 249.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Zoom Alphafly NEXT% sono le scarpe da maratona più avanzate mai realizzate, progettate per la massima prestazione.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7776f88c-1bf6-49ac-a53b-b532f4c51a87/scarpa-da-gara-su-strada-alphafly-3-xn6gMg.png",
            "nuovo_arrivi": true,
        },
        {
            "id": 39,
            "nome": "Nike Air Max 1",
            "categoria": "Sneakers",
            "prezzo": 129.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max 1 sono le iconiche scarpe da corsa che hanno rivoluzionato il mondo delle sneaker, con un design unico e confortevole.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/73438f5c-8fa8-4bd2-9676-ac206c90b691/scarpa-air-max-1-bRwLfj.png",
           "best_seller": 5,

        },
        {
            "id": 40,
            "nome": "Nike Air Max Plus 2",
            "categoria": "Sneakers",
            "prezzo": 179.99,
            "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
            "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
            "descrizione": "Le Nike Air Max Plus 2 sono il rinnovamento delle iconiche Air Max Plus, con un'ammortizzazione Max Air e uno stile unico.",
            "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a41e1440-4644-46f7-83b6-32725f91591c/scarpa-air-max-plus-kpMLxF.png",
            "nuovo_arrivi": true,
        },
        {
          "id": 41,
          "nome": "Nike Air Max 720",
          "categoria": "Sneakers",
          "prezzo": 169.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Max 720 offrono un'ammortizzazione Air Max a tutta lunghezza, per un comfort e uno stile senza precedenti.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f8a4ce8f-d476-4131-b3f8-6b878054a3de/scarpa-air-max-solo-Vmqkb9.png",
          "best_seller": 5,

      },
      {
          "id": 42,
          "nome": "Nike Air Zoom Victory",
          "categoria": "Running",
          "prezzo": 179.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Zoom Victory sono scarpe da corsa progettate per la velocità e il comfort, ideali per le gare su strada.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/01e255e2-8344-423d-98e3-0a0fccc264da/scarpa-chiodata-per-le-gare-sulla-distanza-air-zoom-victory-5zr3gd.png",
          "nuovo_arrivi": true,
      },
      {
          "id": 43,
          "nome": "Nike Air Force 1 High",
          "categoria": "Sneakers",
          "prezzo": 129.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Force 1 High sono un'icona dello stile urbano, con un'ammortizzazione Air-Sole per il massimo comfort.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0ca943b5-2488-4aa4-b980-cd4179ae2d3f/duckboot-lunar-force-1-9LvXwG.png",
          "best_seller": 5,

      },
      {
          "id": 44,
          "nome": "Nike Free RN 5.0",
          "categoria": "Running",
          "prezzo": 99.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Free RN 5.0 sono scarpe da corsa leggere e flessibili, ideali per allenamenti e percorsi naturali.",
          "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bed45cdc-fe4c-4eb1-828e-ff6a4184970c/scarpa-da-running-su-strada-free-run-5-GlfMlr.png",

          "nuovo_arrivi": true,
      },
      {
          "id": 45,
          "nome": "Nike Air Max Sequent 3",
          "categoria": "Sneakers",
          "prezzo": 129.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Max Sequent 3 sono scarpe da corsa comode e versatili, con un'ammortizzazione reattiva per prestazioni ottimali.",
          "immagine": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/vh2qt1h8jhgyw2tyi7ff/scarpa-air-max-sequent-3-gXTO91or.png",
          "best_seller": 5,

      },
      {
          "id": 46,
          "nome": "Nike Air Zoom Freak 1",
          "categoria": "Basket",
          "prezzo": 119.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Zoom Freak 1 sono scarpe da basket con un'ammortizzazione reattiva e un supporto ottimale, per massima performance in campo.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/57b5b542-2e3d-481a-864c-46deb156a17c/scarpa-da-basket-giannis-immortality-3-made-in-sepolia-tKBNxg.png",
          "nuovo_arrivi": true,
      },
      {
          "id": 47,
          "nome": "Nike Air Max 98",
          "categoria": "Sneakers",
          "prezzo": 179.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Max 98 sono scarpe da corsa con un design audace e un'ammortizzazione Air Max a tutta lunghezza.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7437e33d-fcc8-46a6-82d4-16ed34370b6f/scarpa-air-max-97-frVmb5.png",
          "best_seller": 5,

      },
      {
          "id": 48,
          "nome": "Nike Zoom Freak 2",
          "categoria": "Basket",
          "prezzo": 129.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Zoom Freak 2 sono scarpe da basket con un'ammortizzazione reattiva e un design ispirato alla potenza di Giannis Antetokounmpo.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ef4f26cf-7480-4e92-806a-d4341771b591/scarpa-da-basket-giannis-immortality-3-VB6gVH.png",
          "nuovo_arrivi": true,
      },
      {
          "id": 49,
          "nome": "Nike Air Max Axis",
          "categoria": "Sneakers",
          "prezzo": 99.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Air Max Axis sono scarpe da corsa ispirate al design degli anni '90, con un'ammortizzazione Air Max e uno stile retrò.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4763b078-c16f-44bd-a5d0-2fcad00b653c/scarpa-air-max-excee-9RM6nF.png",
          "nuovo_arrivi": true,
      },
      {
          "id": 50,
          "nome": "Nike Zoom Pegasus Turbo 2",
          "categoria": "Running",
          "prezzo": 179.99,
          "taglie_disponibili": ["38", "39", "40", "41", "42", "43", "44", "45"],
          "colori_disponibili": ["Nero", "Bianco", "Blu", "Rosso", "Grigio"],
          "descrizione": "Le Nike Zoom Pegasus Turbo 2 sono scarpe da corsa leggere e veloci, con una schiuma ZoomX per un'ammortizzazione reattiva.",
          "immagine": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/39bc2d92-446a-4c28-a3d4-a75726ee8499/scarpa-da-running-su-strada-pegasus-40-M88nP6.png",
          "nuovo_arrivi": true,
      }
      

    ]
